# Generated by Django 4.2.7 on 2023-11-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sabores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('sabor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sabores.sabor')),
            ],
        ),
    ]
